#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Nov 21, 2018 09:38:43 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import filename_change_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    filename_change_support.set_Tk_var()
    top = Toplevel1 (root)
    filename_change_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    filename_change_support.set_Tk_var()
    top = Toplevel1 (w)
    filename_change_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1184x751+619+320")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        top.bind('<Key-Alt_L>x',lambda e:filename_change_support.quit_file_name_change(e))

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.051, rely=0.053, height=26, width=92)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''From pattern''')

        self.from_pattern_entry = tk.Entry(top)
        self.from_pattern_entry.place(relx=0.051, rely=0.107, height=24
                , relwidth=0.358)
        self.from_pattern_entry.configure(background="white")
        self.from_pattern_entry.configure(disabledforeground="#a3a3a3")
        self.from_pattern_entry.configure(font="TkFixedFont")
        self.from_pattern_entry.configure(foreground="#000000")
        self.from_pattern_entry.configure(highlightbackground="#d9d9d9")
        self.from_pattern_entry.configure(highlightcolor="black")
        self.from_pattern_entry.configure(insertbackground="black")
        self.from_pattern_entry.configure(selectbackground="#c4c4c4")
        self.from_pattern_entry.configure(selectforeground="black")
        self.from_pattern_entry.configure(width=424)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.456, rely=0.053, height=26, width=75)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''To pattern''')

        self.to_pattern_entry = tk.Entry(top)
        self.to_pattern_entry.place(relx=0.456, rely=0.107, height=24
                , relwidth=0.274)
        self.to_pattern_entry.configure(background="white")
        self.to_pattern_entry.configure(disabledforeground="#a3a3a3")
        self.to_pattern_entry.configure(font="TkFixedFont")
        self.to_pattern_entry.configure(foreground="#000000")
        self.to_pattern_entry.configure(highlightbackground="#d9d9d9")
        self.to_pattern_entry.configure(highlightcolor="black")
        self.to_pattern_entry.configure(insertbackground="black")
        self.to_pattern_entry.configure(selectbackground="#c4c4c4")
        self.to_pattern_entry.configure(selectforeground="black")
        self.to_pattern_entry.configure(width=324)

        self.style.configure('Treeview.Heading',  font="TkDefaultFont")
        self.change_scrolledtreeview = ScrolledTreeView(top)
        self.change_scrolledtreeview.place(relx=0.051, rely=0.186
                , relheight=0.648, relwidth=0.912)
        self.change_scrolledtreeview.configure(columns="col")
        self.change_scrolledtreeview.heading("#0",anchor="center")
        self.change_scrolledtreeview.column("#0",width="1057")
        self.change_scrolledtreeview.column("#0",minwidth="20")
        self.change_scrolledtreeview.column("#0",stretch="1")
        self.change_scrolledtreeview.column("#0",anchor="w")
        self.change_scrolledtreeview.heading("col",anchor="center")
        self.change_scrolledtreeview.column("col",width="200")
        self.change_scrolledtreeview.column("col",minwidth="20")
        self.change_scrolledtreeview.column("col",stretch="1")
        self.change_scrolledtreeview.column("col",anchor="w")

        self.preview_button = tk.Button(top)
        self.preview_button.place(relx=0.76, rely=0.107, height=33, width=63)
        self.preview_button.configure(activebackground="#d9d9d9")
        self.preview_button.configure(activeforeground="#000000")
        self.preview_button.configure(background="#d9d9d9")
        self.preview_button.configure(command=filename_change_support.preview_change)
        self.preview_button.configure(disabledforeground="#a3a3a3")
        self.preview_button.configure(foreground="#000000")
        self.preview_button.configure(highlightbackground="#d9d9d9")
        self.preview_button.configure(highlightcolor="black")
        self.preview_button.configure(pady="0")
        self.preview_button.configure(text='''Preview''')

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.473, rely=0.919, height=33, width=109)
        self.Button2.configure(activebackground="#d86643")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d2d81c")
        self.Button2.configure(command=filename_change_support.change_file_names)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Change names''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.068, rely=0.866, height=26, width=84)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''From count:''')

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.372, rely=0.866, height=26, width=67)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''To: count''')

        self.from_count_entry = tk.Entry(top)
        self.from_count_entry.place(relx=0.16, rely=0.866, height=24
                , relwidth=0.172)
        self.from_count_entry.configure(background="white")
        self.from_count_entry.configure(disabledforeground="#a3a3a3")
        self.from_count_entry.configure(font="TkFixedFont")
        self.from_count_entry.configure(foreground="#000000")
        self.from_count_entry.configure(highlightbackground="#d9d9d9")
        self.from_count_entry.configure(highlightcolor="black")
        self.from_count_entry.configure(insertbackground="black")
        self.from_count_entry.configure(selectbackground="#c4c4c4")
        self.from_count_entry.configure(selectforeground="black")

        self.to_count_entry = tk.Entry(top)
        self.to_count_entry.place(relx=0.465, rely=0.866, height=24
                , relwidth=0.172)
        self.to_count_entry.configure(background="white")
        self.to_count_entry.configure(disabledforeground="#a3a3a3")
        self.to_count_entry.configure(font="TkFixedFont")
        self.to_count_entry.configure(foreground="#000000")
        self.to_count_entry.configure(highlightbackground="#d9d9d9")
        self.to_count_entry.configure(highlightcolor="black")
        self.to_count_entry.configure(insertbackground="black")
        self.to_count_entry.configure(selectbackground="#c4c4c4")
        self.to_count_entry.configure(selectforeground="black")

        self.escape_checkbutton = tk.Checkbutton(top)
        self.escape_checkbutton.place(relx=0.819, rely=0.107, relheight=0.041
                , relwidth=0.128)
        self.escape_checkbutton.configure(activebackground="#d9d9d9")
        self.escape_checkbutton.configure(activeforeground="#000000")
        self.escape_checkbutton.configure(background="#d9d9d9")
        self.escape_checkbutton.configure(disabledforeground="#a3a3a3")
        self.escape_checkbutton.configure(foreground="#000000")
        self.escape_checkbutton.configure(highlightbackground="#d9d9d9")
        self.escape_checkbutton.configure(highlightcolor="black")
        self.escape_checkbutton.configure(justify='left')
        self.escape_checkbutton.configure(offvalue="off")
        self.escape_checkbutton.configure(onvalue="on")
        self.escape_checkbutton.configure(text='''Escape from string''')
        self.escape_checkbutton.configure(variable=filename_change_support.check_escape)

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledTreeView(AutoScroll, ttk.Treeview):
    '''A standard ttk Treeview widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        ttk.Treeview.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





