#############################################################################
# Generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#  Nov 22, 2018 12:09:39 AM CST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1762x983+575+235
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2564 1415
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Multi-Category Library"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    bind $top <Key-Alt_L>x {
        lambda e: quit_app(e)
    }
    bind $top <Key-Control_L>c {
        lambda e: open_filename_change(e)
    }
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Books 
    vTcl:DefineAlias "$top.lab43" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure Treeview.Heading -background #d9d9d9
    ttk::style configure Treeview.Heading -font TkDefaultFont
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $top.scr43 \
        -background {#d9d9d9} -height 777 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 320 
    vTcl:DefineAlias "$top.scr43" "cat_scrolledtreeview" vTcl:WidgetProc "Toplevel1" 1
    bind $top.scr43 <Key-Return> {
        lambda e: search_book_in_category(e)
    }
    label $top.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Categories 
    vTcl:DefineAlias "$top.lab44" "Label2" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr46 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr46" "tag_candidate_scrolledlistbox" vTcl:WidgetProc "Toplevel1" 1
    bind $top.scr46 <Key-Return> {
        lambda e: add_tag_2_cat(e)
    }

    $top.scr46.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    label $top.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Tag Candidates} 
    vTcl:DefineAlias "$top.lab47" "Label3" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure Treeview.Heading -background #d9d9d9
    ttk::style configure Treeview.Heading -font TkDefaultFont
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $top.scr44 \
        -background {#d9d9d9} -height 15 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 30 
    vTcl:DefineAlias "$top.scr44" "books_scrolledtreeview" vTcl:WidgetProc "Toplevel1" 1
    bind $top.scr44 <ButtonRelease-1> {
        lambda e: record_title(e)
    }
    bind $top.scr44 <KeyRelease> {
        lambda e: all_book_view_control(e)
    }
    button $top.but43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command cmd_save_category \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Save Category} 
    vTcl:DefineAlias "$top.but43" "Button4" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure Treeview.Heading -background #d9d9d9
    ttk::style configure Treeview.Heading -font TkDefaultFont
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $top.scr47 \
        -background {#d9d9d9} -height 15 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 30 
    vTcl:DefineAlias "$top.scr47" "search_books_scrolledtreeview" vTcl:WidgetProc "Toplevel1" 1
    bind $top.scr47 <ButtonRelease-1> {
        lambda e: pick_searched_item(e)
    }
    bind $top.scr47 <KeyRelease> {
        lambda e: search_book_view_control(e)
    }
    label $top.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Found Books in category} 
    vTcl:DefineAlias "$top.lab48" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Chosen Tags} 
    vTcl:DefineAlias "$top.lab50" "Label3_3" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr51 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr51" "chosen_tag_scrolledlistbox" vTcl:WidgetProc "Toplevel1" 1
    bind $top.scr51 <Key-Return> {
        lambda e: remove_tag_4_search(e)
    }

    $top.scr51.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    entry $top.ent43 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent43" "filename_entry" vTcl:WidgetProc "Toplevel1" 1
    button $top.but44 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command change_file_name \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Change file name} 
    vTcl:DefineAlias "$top.but44" "Button_remove_space" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command rescan_folder \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Rescan folder} 
    vTcl:DefineAlias "$top.but46" "Button3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent47 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent47" "all_book_count_entry" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent48 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent48" "found_book_count_entry" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent49 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent49" "search_string_entry" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command search_file_name \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Search Files} 
    vTcl:DefineAlias "$top.but47" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {File Details} 
    vTcl:DefineAlias "$top.lab49" "Label4" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent50 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent50" "file_detail_entry" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent44 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent44" "manual_tag_entry" vTcl:WidgetProc "Toplevel1" 1
    bind $top.ent44 <Key-Return> {
        lambda e: add_tag_e(e)
    }
    button $top.but48 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command add_tag -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Add tag} 
    vTcl:DefineAlias "$top.but48" "Button_tag" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr49 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr49" "file_tags_scrolledlistbox" vTcl:WidgetProc "Toplevel1" 1
    bind $top.scr49 <Key-Return> {
        lambda e: remove_file_tag(e)
    }

    $top.scr49.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    button $top.but45 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command set_tag_as_sub \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Subject Cat} 
    vTcl:DefineAlias "$top.but45" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but49 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command set_tag_as_obj \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Object Cat} 
    vTcl:DefineAlias "$top.but49" "Button5" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent51 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent51" "sub_cat_entry" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent52 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent52" "obj_cat_entry" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command swap_tags \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text <-> 
    vTcl:DefineAlias "$top.but53" "Button6" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che55 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text contains \
        -variable check_cat_contains 
    vTcl:DefineAlias "$top.che55" "check_contain_checkbutton" vTcl:WidgetProc "Toplevel1" 1
    button $top.but56 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command add_cat_relation \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Add Cat Relation} 
    vTcl:DefineAlias "$top.but56" "Button7" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 1260 -y 40 -width 46 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.scr43 \
        -in $top -x 50 -y 92 -width 320 -relwidth 0 -height 777 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 40 -y 30 -anchor nw -bordermode ignore 
    place $top.scr46 \
        -in $top -x 1110 -y 366 -width 125 -relwidth 0 -height 507 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 1110 -y 90 -width 109 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.scr44 \
        -in $top -x 1260 -y 120 -width 470 -relwidth 0 -height 837 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but43 \
        -in $top -x 166 -y 20 -width 107 -height 33 -anchor nw \
        -bordermode ignore 
    place $top.scr47 \
        -in $top -x 570 -y 121 -width 500 -relwidth 0 -height 837 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 558 -y 83 -width 206 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 427 -y 59 -width 109 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.scr51 \
        -in $top -x 420 -y 100 -width 125 -relwidth 0 -height 537 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent43 \
        -in $top -x 1270 -y 80 -width 424 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but44 \
        -in $top -x 1100 -y 900 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 424 -y 20 -width 102 -height 33 -anchor nw \
        -bordermode ignore 
    place $top.ent47 \
        -in $top -x 1350 -y 40 -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 770 -y 84 -width 204 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.ent49 \
        -in $top -x 560 -y 20 -width 454 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 1040 -y 20 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 390 -y 753 -width 79 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.ent50 \
        -in $top -x 380 -y 794 -width 174 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent44 \
        -in $top -x 1105 -y 130 -width 134 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 1120 -y 170 -anchor nw -bordermode ignore 
    place $top.scr49 \
        -in $top -x 1110 -y 220 -width 125 -relwidth 0 -height 117 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 60 -y 890 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 160 -y 890 -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 60 -y 940 -width 194 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent52 \
        -in $top -x 325 -y 940 -width 204 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but53 \
        -in $top -x 267 -y 939 -width 38 -height 33 -anchor nw \
        -bordermode ignore 
    place $top.che55 \
        -in $top -x 310 -y 890 -width 84 -height 31 -anchor nw \
        -bordermode ignore 
    place $top.but56 \
        -in $top -x 420 -y 890 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

